name: ShopSphere CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Backend
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Build Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: shopsphere-backend:latest

      - name: Build Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          tags: shopsphere-frontend:latest